import React, { useState } from 'react';
import { FiMail, FiSmartphone, FiPhone, FiCheck } from 'react-icons/fi';

interface VerificationModalProps {
  isOpen: boolean;
  onClose: () => void;
  onVerificationSuccess: () => void;
  onShowSuccess: () => void;
  withdrawData?: any;
}

type VerificationMethod = 'email' | 'authenticator' | 'phone';
type ModalStep = 'select' | 'verify';

const VERIFICATION_METHODS = [
  {
    id: 'email' as VerificationMethod,
    title: 'Email',
    description: '******* @gmail.com',
    icon: FiMail,
    enabled: true
  },
  {
    id: 'authenticator' as VerificationMethod,
    title: 'Authenticator app',
    description: '',
    icon: FiSmartphone,
    enabled: true
  },
  {
    id: 'phone' as VerificationMethod,
    title: 'Phone number',
    description: '+234****946',
    icon: FiPhone,
    enabled: false
  }
];

export default function VerificationModal({ 
  isOpen, 
  onClose, 
  onVerificationSuccess,
  onShowSuccess,
  withdrawData 
}: VerificationModalProps) {
  const [currentStep, setCurrentStep] = useState<ModalStep>('select');
  const [selectedMethod, setSelectedMethod] = useState<VerificationMethod>('authenticator');
  const [verificationCode, setVerificationCode] = useState('');
  const [isVerifying, setIsVerifying] = useState(false);

  if (!isOpen) return null;

  const handleMethodSelect = (method: VerificationMethod) => {
    setSelectedMethod(method);
  };

  const handleContinue = () => {
    setCurrentStep('verify');
  };

  const handleBack = () => {
    setCurrentStep('select');
    setVerificationCode('');
  };

  const handleSubmit = async () => {
    if (!verificationCode.trim()) return;
    
    setIsVerifying(true);
    
    // Simulate verification process
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    setIsVerifying(false);
    onVerificationSuccess();
    onShowSuccess();
    handleClose();
  };

  const handleClose = () => {
    setCurrentStep('select');
    setSelectedMethod('authenticator');
    setVerificationCode('');
    setIsVerifying(false);
    onClose();
  };

  const handleResendCode = () => {
    // Simulate resending code
    console.log('Resending verification code...');
  };

  const getVerificationTitle = () => {
    switch (selectedMethod) {
      case 'email':
        return 'Email Verification';
      case 'authenticator':
        return 'Authenticator App Verification';
      case 'phone':
        return 'Phone Verification';
      default:
        return 'Verification';
    }
  };

  const getVerificationDescription = () => {
    switch (selectedMethod) {
      case 'email':
        return 'We sent a 6-digit code to dino@gmail.com';
      case 'authenticator':
        return 'Enter the 6-digit code generated by the authenticator app.';
      case 'phone':
        return 'We sent a 6-digit code to +234****946';
      default:
        return '';
    }
  };

  return (
    <div 
      className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
      onClick={(e) => {
        if (e.target === e.currentTarget) {
          handleClose();
        }
      }}
    >
      <div className="bg-white rounded-xl w-full max-w-sm">
        <div className="p-6">
          {/* Header */}
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold text-gray-900">
              {currentStep === 'select' ? 'Select Verification Method' : getVerificationTitle()}
            </h2>
            <button 
              onClick={handleClose}
              className="text-gray-400 hover:text-gray-600"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          {currentStep === 'select' ? (
            <>
              {/* Subtitle */}
              <p className="text-sm text-gray-600 mb-6">
                Please select ALL the security methods that are unavailable and you would like to reset.
              </p>

              {/* Verification Methods */}
              <div className="space-y-3 mb-6">
                {VERIFICATION_METHODS.map((method) => (
                  <button
                    key={method.id}
                    onClick={() => method.enabled && handleMethodSelect(method.id)}
                    disabled={!method.enabled}
                    className={`w-full flex items-center gap-3 p-3 border rounded-lg text-left transition-colors ${
                      method.enabled 
                        ? selectedMethod === method.id
                          ? 'border-teal-500 bg-teal-50'
                          : 'border-gray-200 hover:border-gray-300'
                        : 'border-gray-200 bg-gray-50 cursor-not-allowed opacity-60'
                    }`}
                  >
                    <div className={`flex-shrink-0 ${method.enabled ? 'text-gray-600' : 'text-gray-400'}`}>
                      <method.icon className="w-5 h-5" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className={`font-medium ${method.enabled ? 'text-gray-900' : 'text-gray-500'}`}>
                        {method.title}
                      </div>
                      {method.description && (
                        <div className={`text-sm ${method.enabled ? 'text-gray-500' : 'text-gray-400'}`}>
                          {method.description}
                        </div>
                      )}
                    </div>
                    {method.enabled && selectedMethod === method.id && (
                      <div className="flex-shrink-0">
                        <div className="w-5 h-5 bg-teal-500 rounded-full flex items-center justify-center">
                          <FiCheck className="w-3 h-3 text-white" />
                        </div>
                      </div>
                    )}
                  </button>
                ))}
              </div>

              {/* Continue Button */}
              <button
                onClick={handleContinue}
                className="w-full bg-teal-600 hover:bg-teal-700 text-white py-3 rounded-lg font-medium transition-colors"
              >
                Continue
              </button>
            </>
          ) : (
            <>
              {/* Back Button */}
              <button
                onClick={handleBack}
                className="flex items-center gap-2 text-gray-600 hover:text-gray-900 mb-4"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7" />
                </svg>
                <span className="text-sm">Back</span>
              </button>

              {/* Description */}
              <p className="text-sm text-gray-600 mb-6">
                {getVerificationDescription()}
              </p>

              {/* Code Input */}
              <div className="mb-4">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  {selectedMethod === 'authenticator' ? 'Input 6-digit code' : 'Code'}
                </label>
                <div className="relative">
                  <input
                    type="text"
                    value={verificationCode}
                    onChange={(e) => setVerificationCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
                    className="w-full px-3 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-teal-500 focus:border-teal-500 text-center text-lg font-mono tracking-widest"
                    placeholder="000000"
                    maxLength={6}
                  />
                  {selectedMethod !== 'authenticator' && (
                    <button
                      onClick={handleResendCode}
                      className="absolute right-3 top-1/2 transform -translate-y-1/2 text-teal-600 hover:text-teal-700 text-sm font-medium"
                    >
                      Resend
                    </button>
                  )}
                </div>
                {selectedMethod === 'email' && (
                  <p className="text-xs text-gray-500 mt-1">
                    Didn't receive the 6-digit code? <button onClick={handleResendCode} className="text-teal-600 hover:text-teal-700">Click to resend</button>
                  </p>
                )}
              </div>

              {/* Submit Button */}
              <button
                onClick={handleSubmit}
                disabled={verificationCode.length !== 6 || isVerifying}
                className="w-full bg-teal-600 hover:bg-teal-700 disabled:bg-gray-300 disabled:cursor-not-allowed text-white py-3 rounded-lg font-medium transition-colors"
              >
                {isVerifying ? 'Verifying...' : 'Submit'}
              </button>
            </>
          )}
        </div>
      </div>
    </div>
  );
}