export type InsightType = "Bullish" | "Bearish" | "Neutral";

type Insight = {
  id: number;
  title: string;
  description: string;
  date: string;
  type: InsightType;
  readingTime: string;
  image: string;
  source: string;
  bookmark: boolean;
}[];

export const insightsData: Insight = [
  {
    id: 1,
    title: "Bill Walsh leadership lessons",
    description: "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
    date: "17 Jan 2025",
    type: "Neutral",
    readingTime: "5 min read",
    image: "/assets/images/website/default-insight.jpg",
    source: "Derived from X",
    bookmark: false,
  },
  {
    id: 2,
    title: "Bill Walsh leadership lessons",
    description: "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
    date: "17 Jan 2025",
    type: "Bullish",
    readingTime: "5 min read",
    image: "/assets/images/website/default-insight.jpg",
    source: "Derived from X",
    bookmark: false,
  },
  {
    id: 3,
    title: "Bill Walsh leadership lessons",
    description: "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
    date: "17 Jan 2025",
    type: "Bearish",
    readingTime: "5 min read",
    image: "/assets/images/website/default-insight.jpg",
    source: "Derived from X",
    bookmark: false,
  },
  {
    id: 4,
    title: "Bill Walsh leadership lessons",
    description: "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
    date: "17 Jan 2025",
    type: "Neutral",
    readingTime: "5 min read",
    image: "/assets/images/website/default-insight.jpg",
    source: "Derived from X",
    bookmark: false,
  },
  {
    id: 5,
    title: "Bill Walsh leadership lessons",
    description: "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
    date: "17 Jan 2025",
    type: "Bearish",
    readingTime: "5 min read",
    image: "/assets/images/website/default-insight.jpg",
    source: "Derived from X",
    bookmark: false,
  },
  {
    id: 6,
    title: "Bill Walsh leadership lessons",
    description: "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
    date: "17 Jan 2025",
    type: "Bullish",
    readingTime: "5 min read",
    image: "/assets/images/website/default-insight.jpg",
    source: "Derived from X",
    bookmark: false,
  },
  {
    id: 7,
    title: "Bill Walsh leadership lessons",
    description: "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
    date: "17 Jan 2025",
    type: "Bearish",
    readingTime: "5 min read",
    image: "/assets/images/website/default-insight.jpg",
    source: "Derived from X",
    bookmark: false,
  },
  {
    id: 8,
    title: "Bill Walsh leadership lessons",
    description: "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
    date: "17 Jan 2025",
    type: "Neutral",
    readingTime: "5 min read",
    image: "/assets/images/website/default-insight.jpg",
    source: "Derived from X",
    bookmark: false,
  },
  {
    id: 9,
    title: "Bill Walsh leadership lessons",
    description: "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
    date: "17 Jan 2025",
    type: "Bullish",
    readingTime: "5 min read",
    image: "/assets/images/website/default-insight.jpg",
    source: "Derived from X",
    bookmark: false,
  },
  {
    id: 10,
    title: "Bill Walsh leadership lessons",
    description: "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
    date: "17 Jan 2025",
    type: "Neutral",
    readingTime: "5 min read",
    image: "/assets/images/website/default-insight.jpg",
    source: "Derived from X",
    bookmark: false,
  },
  {
    id: 11,
    title: "Bill Walsh leadership lessons",
    description: "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
    date: "17 Jan 2025",
    type: "Bullish",
    readingTime: "5 min read",
    image: "/assets/images/website/default-insight.jpg",
    source: "Derived from X",
    bookmark: false,
  },
  {
    id: 12,
    title: "Bill Walsh leadership lessons",
    description: "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
    date: "17 Jan 2025",
    type: "Bearish",
    readingTime: "5 min read",
    image: "/assets/images/website/default-insight.jpg",
    source: "Derived from X",
    bookmark: false,
  },
  {
    id: 13,
    title: "Bill Walsh leadership lessons",
    description: "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
    date: "17 Jan 2025",
    type: "Neutral",
    readingTime: "5 min read",
    image: "/assets/images/website/default-insight.jpg",
    source: "Derived from X",
    bookmark: false,
  },
  {
    id: 14,
    title: "Bill Walsh leadership lessons",
    description: "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
    date: "17 Jan 2025",
    type: "Bearish",
    readingTime: "5 min read",
    image: "/assets/images/website/default-insight.jpg",
    source: "Derived from X",
    bookmark: false,
  },
  {
    id: 15,
    title: "Bill Walsh leadership lessons",
    description: "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
    date: "17 Jan 2025",
    type: "Bullish",
    readingTime: "5 min read",
    image: "/assets/images/website/default-insight.jpg",
    source: "Derived from X",
    bookmark: false,
  },
]